apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-django
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-django
  ports:
    - port: 80
      targetPort: {{ .Values.service.port }}

