{{- range .Values.applications }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: {{ .project | default "default" }}
  source:
    repoURL: {{ .source.repoURL }}
    path: {{ .source.path }}
    targetRevision: {{ .source.targetRevision | default "main" }}
  destination:
    server: {{ .destination.server | default "https://kubernetes.default.svc" }}
    namespace: {{ .destination.namespace | default "default" }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
{{- end }}
